"""HTML audit report reporter."""

from __future__ import annotations

import html
from pathlib import Path
from typing import Optional

from secrulekit.validators.rule_validator import ValidationResult, Severity


class HtmlReporter:
    """Generate an HTML audit report from validation results."""

    def generate(self, result: ValidationResult, output: Optional[Path | str] = None) -> str:
        rows = ""
        for f in result.findings:
            color = {
                Severity.ERROR: "#dc3545",
                Severity.WARNING: "#fd7e14",
                Severity.INFO: "#0d6efd",
            }.get(f.severity, "#6c757d")
            rows += (
                f"<tr>"
                f"<td><span style='color:{color};font-weight:600'>{html.escape(f.severity.value.upper())}</span></td>"
                f"<td><code>{html.escape(f.code)}</code></td>"
                f"<td>{html.escape(f.rule_name or '')}</td>"
                f"<td>{html.escape(f.message)}</td>"
                f"<td style='font-size:0.85em'>{html.escape(str(f.file) if f.file else '')}:{f.line if f.line else ''}</td>"
                f"</tr>\n"
            )

        passed_color = "#198754" if result.passed else "#dc3545"
        passed_text = "PASSED" if result.passed else "FAILED"

        page = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SecRuleKit Validation Report</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 2rem; background: #f8f9fa; }}
    h1 {{ color: #212529; }}
    .badge {{ display:inline-block; padding:.3em .6em; border-radius:.4em; color:#fff; font-size:.9em; font-weight:600; }}
    .summary {{ display:flex; gap:1.5rem; margin:1.5rem 0; flex-wrap:wrap; }}
    .card {{ background:#fff; border-radius:.5rem; padding:1rem 1.5rem; box-shadow:0 1px 3px rgba(0,0,0,.1); min-width:120px; }}
    .card .num {{ font-size:2rem; font-weight:700; }}
    table {{ width:100%; border-collapse:collapse; background:#fff; border-radius:.5rem; overflow:hidden; box-shadow:0 1px 3px rgba(0,0,0,.1); }}
    th {{ background:#343a40; color:#fff; padding:.75rem 1rem; text-align:left; }}
    td {{ padding:.65rem 1rem; border-bottom:1px solid #dee2e6; font-size:.9em; }}
    tr:last-child td {{ border-bottom:none; }}
    code {{ background:#e9ecef; padding:.1em .3em; border-radius:.2em; font-size:.9em; }}
  </style>
</head>
<body>
  <h1>SecRuleKit Validation Report</h1>
  <p>Result: <span class="badge" style="background:{passed_color}">{passed_text}</span></p>

  <div class="summary">
    <div class="card">
      <div class="num" style="color:#198754">{result.valid_count}</div>
      <div>Valid rules</div>
    </div>
    <div class="card">
      <div class="num" style="color:#dc3545">{result.error_count}</div>
      <div>Errors</div>
    </div>
    <div class="card">
      <div class="num" style="color:#fd7e14">{result.warning_count}</div>
      <div>Warnings</div>
    </div>
  </div>

  <table>
    <thead>
      <tr><th>Severity</th><th>Code</th><th>Rule</th><th>Message</th><th>Location</th></tr>
    </thead>
    <tbody>
      {rows if rows else '<tr><td colspan="5" style="text-align:center;color:#6c757d">No findings</td></tr>'}
    </tbody>
  </table>

  <p style="margin-top:2rem;color:#6c757d;font-size:.85em">
    Generated by <a href="https://github.com/lkop32788/SecRuleKit">SecRuleKit</a>
  </p>
</body>
</html>"""

        if output:
            Path(output).write_text(page, encoding="utf-8")
        return page
